import json
import csv
import os


def load_judgments():
    with open("data/ai_judgments.json", "r", encoding="utf-8") as f:
        return json.load(f)


def generate_csv(data):
    """Generate CSV with clear separation: FACTS vs AI JUDGMENT."""
    os.makedirs("reports", exist_ok=True)
    filename = "reports/audit_report.csv"

    with open(filename, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "Website", "Status", "Title", "Meta Description",
            "Load Time (s)", "H1 Count", "H2 Count", "Total Links",
            "Images Missing Alt", "Has Email", "Has Phone",
            "AI Score", "AI Priority", "AI Score Reasoning",
            "AI Missing Features", "AI Recommendations",
        ])

        for entry in data:
            url = entry["url"]

            if entry["status"] != "success":
                writer.writerow([
                    url, "FAILED",
                    entry["data"].get("error", "Unknown error"),
                    "", "", "", "", "", "", "", "",
                    entry["ai_judgment"].get("score", "N/A"),
                    entry["ai_judgment"].get("priority", "N/A"),
                    entry["ai_judgment"].get("score_reasoning", ""),
                    "", "; ".join(entry["ai_judgment"].get("recommendations", []))
                ])
                continue

            d = entry["data"]
            ai = entry["ai_judgment"]

            writer.writerow([
                url, "OK",
                d.get("title", ""),
                d.get("meta_description", ""),
                d.get("load_time_seconds", ""),
                d.get("h1_count", ""),
                d.get("h2_count", ""),
                d.get("total_links", ""),
                d.get("images_missing_alt", ""),
                d.get("has_email_pattern", ""),
                d.get("has_phone_pattern", ""),
                ai.get("score", "N/A"),
                ai.get("priority", "N/A"),
                ai.get("score_reasoning", ""),
                "; ".join(ai.get("missing_features", [])),
                "; ".join(ai.get("recommendations", []))
            ])

    print(f"✓ CSV report: {filename}")


def generate_html(data):
    """Generate a clean HTML report."""
    filename = "reports/audit_report.html"

    html = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Education Website Audit Report</title>
<style>
    body { font-family: -apple-system, Segoe UI, Arial, sans-serif; margin: 40px; background: #f5f7fa; color: #222; }
    h1 { color: #2c3e50; }
    .summary { background: #fff; padding: 15px 20px; border-radius: 8px; margin-bottom: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
    .summary span { font-weight: bold; color: #2c3e50; }
    .card { background: #fff; padding: 20px; margin-bottom: 20px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
    .card h2 { margin-top: 0; font-size: 18px; color: #2c3e50; word-break: break-all; }
    .score { font-size: 28px; font-weight: bold; padding: 6px 14px; border-radius: 6px; display: inline-block; }
    .score-high { background: #d4edda; color: #155724; }
    .score-mid  { background: #fff3cd; color: #856404; }
    .score-low  { background: #f8d7da; color: #721c24; }
    .score-na   { background: #e2e3e5; color: #383d41; }
    .section { margin-top: 15px; }
    .section h3 { font-size: 14px; text-transform: uppercase; color: #555; margin-bottom: 6px; letter-spacing: 0.5px; }
    .facts-table { width: 100%; border-collapse: collapse; font-size: 14px; }
    .facts-table td { padding: 4px 8px; border-bottom: 1px solid #eee; }
    .facts-table td:first-child { color: #777; width: 40%; }
    ul { margin: 6px 0; padding-left: 20px; }
    li { font-size: 14px; margin-bottom: 3px; }
    .priority { display: inline-block; padding: 3px 10px; border-radius: 4px; font-size: 13px; font-weight: bold; }
    .p-High { background: #f8d7da; color: #721c24; }
    .p-Medium { background: #fff3cd; color: #856404; }
    .p-Low { background: #d4edda; color: #155724; }
</style>
</head>
<body>
<h1>📊 Education Website Audit Report</h1>
<p>AI-assisted audit — Facts extracted by scraper, Judgments generated by Groq LLM.</p>
"""

    total = len(data)
    success = len([d for d in data if d["status"] == "success"])
    html += f'<div class="summary"><span>Total sites:</span> {total} &nbsp;|&nbsp; <span>Successfully audited:</span> {success} &nbsp;|&nbsp; <span>Failed:</span> {total - success}</div>'

    for entry in data:
        url = entry["url"]
        ai = entry.get("ai_judgment", {})

        html += '<div class="card">'
        html += f'<h2>{url}</h2>'

        if entry["status"] != "success":
            html += f'<p style="color:#721c24;">❌ Scrape failed: {entry["data"].get("error", "Unknown")}</p>'
            html += f'<p><b>AI Recommendation:</b> {"; ".join(ai.get("recommendations", []))}</p>'
            html += '</div>'
            continue

        d = entry["data"]
        score = ai.get("score")
        priority = ai.get("priority", "N/A")

        if score is None:
            score_class, score_text = "score-na", "N/A"
        elif score >= 75:
            score_class, score_text = "score-high", f"{score}/100"
        elif score >= 50:
            score_class, score_text = "score-mid", f"{score}/100"
        else:
            score_class, score_text = "score-low", f"{score}/100"

        html += f'<span class="score {score_class}">{score_text}</span>'
        html += f' &nbsp; Priority: <span class="priority p-{priority}">{priority}</span>'
        html += f'<p style="margin-top:12px;"><i>{ai.get("score_reasoning", "")}</i></p>'

        html += '<div class="section"><h3>📋 Facts (measured by script)</h3>'
        html += '<table class="facts-table">'
        html += f'<tr><td>Title</td><td>{d.get("title","")}</td></tr>'
        html += f'<tr><td>Meta Description</td><td>{d.get("meta_description","")[:120]}</td></tr>'
        html += f'<tr><td>Load Time</td><td>{d.get("load_time_seconds","")}s</td></tr>'
        html += f'<tr><td>H1 / H2 Count</td><td>{d.get("h1_count","")} / {d.get("h2_count","")}</td></tr>'
        html += f'<tr><td>Total Links</td><td>{d.get("total_links","")}</td></tr>'
        html += f'<tr><td>Images Missing Alt</td><td>{d.get("images_missing_alt","")}</td></tr>'
        html += f'<tr><td>Has Email / Phone</td><td>{d.get("has_email_pattern","")} / {d.get("has_phone_pattern","")}</td></tr>'
        html += '</table></div>'

        html += '<div class="section"><h3>🤖 AI Judgment (from Groq LLM)</h3>'
        missing = ai.get("missing_features", [])
        recs = ai.get("recommendations", [])
        html += f'<p><b>Missing Features:</b></p><ul>{"".join(f"<li>{m}</li>" for m in missing) or "<li>None reported</li>"}</ul>'
        html += f'<p><b>Recommendations:</b></p><ul>{"".join(f"<li>{r}</li>" for r in recs) or "<li>None</li>"}</ul>'
        html += '</div>'

        html += '</div>'

    html += '</body></html>'

    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"✓ HTML report: {filename}")


def main():
    data = load_judgments()
    print(f"Loaded {len(data)} records.\n")
    generate_csv(data)
    generate_html(data)
    print("\nDone! Open reports/audit_report.html in your browser.")


if __name__ == "__main__":
    main()